---
title: "DisabilityScams"
output: html_document
date: "2023-07-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Telecommuting(t,f) 
Has_company_logo
Has_questions


```{r cars}
data1 <- read.csv("Data/DataSet.csv", header=TRUE)
data2 <- read.csv("Data/balanced_dataset.csv", header=TRUE)
View(data1)
View(data2)
summary(data1)
summary(data2)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
#plot(pressure)

# Create a bar plot for Telecommuting
ggplot(data2, aes(x = telecommuting)) +
  geom_bar(fill = "blue") +
  labs(x = "Telecommuting", y = "Frequency") +
  ggtitle("Frequency of Telecommuting")

# Create a bar plot for Has_company_logo
ggplot(data2, aes(x = has_company_logo)) +
  geom_bar(fill = "green") +
  labs(x = "Has_company_logo", y = "Frequency") +
  ggtitle("Frequency of Having Company Logo")

# Create a bar plot for Has_questions
ggplot(data2, aes(x = has_questions)) +
  geom_bar(fill = "orange") +
  labs(x = "Has_questions", y = "Frequency") +
  ggtitle("Frequency of Having Questions")
```

```{r}
  # pie(data2$telecommuting, labels = c("t", "f"), main = "Telecommuting")
  # 
  # pie(data2$company_logo, labels = c("t", "f"), main = "Has Company Logo")
  # 
  # pie(data2$has_questions, labels = c("t", "f"), main = "Has Questions")

  values <- c(sum(data2$has_company_logo == 'f'), sum(data2$has_company_logo == 't')) 
  labels <- c("Has Logo", "Doesn't Have Logo") # 
  pie(values, labels = labels, radius = 0.6, donut = TRUE)
  
  values <- c(sum(data2$telecommuting == 'f'), sum(data2$telecommuting == 't')) 
  labels <- c("Has Telecommuting", "Doesn't Have Telecommuting") 
  pie(values, labels = labels, radius = 0.6, donut = TRUE)
  
  values <- c(sum(data2$has_questions == 'f'), sum(data2$has_questions == 't')) 
  labels <- c("Has Questions", "Doesn't Have Questions")
  pie(values, labels = labels, radius = 0.6, donut = TRUE)
```