---
title: "KennethScamBaseCleaning"
author: "Kenneth Ren"
date: "2023-07-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, fig.width=8, fig.height=4)
options(scipen = 999, digits = 5)  # controls base R output

# Package setup
if(!require("pacman")) install.packages("pacman")

pacman::p_load(ISLR, readxl, magrittr, leaps, contrast, car, tidyverse, dplyr, ggplot2, data.table, lubridate, 
               glmnet, kableExtra, stargazer, scales, viridis, knitr, readr, usmap)
```

```{r}
test_data <- read_csv("data/spambase.data")
spambase_names <- read_csv("data/spambase.names")
```


```{r}
rownames(test_data)
```
```{r}
colnames(test_data)
```

HiHi

```{r}
test_data <- data.frame("id" = c(1:4601), test_data)
#test_data$id = c(1:4600)
```

```{r}
colnames(spambase_names)
c(spambase_names$"| SPAM E-MAIL DATABASE ATTRIBUTES (in .names format)"[30:86], "1")
```

```{r}
colnames(test_data) <- c("id", spambase_names$"| SPAM E-MAIL DATABASE ATTRIBUTES (in .names format)"[30:86], "isSpam")
# test_data <- test)data %>% 
#        rename("word_freq_make" = "0...1")
# test_data <- test_data %>% 
#        rename("word_freq_make" = "0.64..2")
# test_data <- test_data %>% 
#        rename("word_freq_make" = "0...1")
# test_data <- test_data %>% 
#        rename("word_freq_make" = "0...1")
# test_data <- test_data %>% 
#        rename("word_freq_make" = "0...1")
# test_data <- test_data %>% 
#        rename("word_freq_make" = "0...1")
```

```{r output}
write.csv(test_data, "data/spambase_data_labeled.csv")
```
